version: '3'
services:
  # post-db:
  #   image: mysql:8.0.17
  #   volumes:
  #     - post-data:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_DATABASE: post_DB
  #     TZ: Asia/Tokyo
  #   ports:
  #     - "4306:3306"
  # post:
  #   build:
  #     context: server/post
  #     dockerfile: Dockerfile.fresh
  #   volumes:
  #     - ./server/post/src:/app
  #   depends_on:
  #     - post-db
  # client:
  #   build:
  #     context: client/
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./client:/app
  #   ports:
  #     - 3000:3000
  #   tty: true
  gateway:
    build:
      context: server/api-gateway
      dockerfile: Dockerfile.fresh
    volumes:
      - ./server/api-gateway/src:/app
    ports:
      - 8080:8080
    # depends_on:
    #   - post-db
    environment:
      GRAPHQL_PORT: 8080
      POST_URL: post:50051
      TIMEOUT: 2
volumes:
  post-data:
    driver: local