apiVersion: skaffold/v1
kind: Config
metadata:
  name: fishapp
build:
  artifacts:
  - image: fishapp_auth
    context: server/auth
    docker: 
      dockerfile: Dockerfile.dev
    sync:
      manual:
      - src: 'src/**/*'
        dest: /app
        strip: src
  - image: fishapp_client_nuxt
    context: client
    docker: 
      dockerfile: Dockerfile.dev
    sync:
      manual:
      - src: 'src/**/*'
        dest: /app
  local:
    useBuildkit: true

deploy:
  kubectl:
    manifests:
    - k8s-dev/local-pv.yml
    - k8s-dev/local-pvc.yml
    - k8s-dev/authapi-config.yml
    - k8s-dev/authapi-secret.yml
    - k8s-dev/auth-db.yml
    - k8s-dev/auth.yml
    - k8s-dev/client.yml
    - k8s-dev/ingress.yml

portForward:
- resourceType: statefulset
  resourceName: auth-db
  port: 3306
  localPort: 5306