apiVersion: v1
kind: PersistentVolume
metadata:
  name: auth-pv
  
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/tmp/fishapp-volume/pv001"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: post-pv
  
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/tmp/fishapp-volume/pv002"