apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fishapp-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: fishapp-external-address # terraformで作成
    networking.gke.io/managed-certificates: fishapp-certificate
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
  - http:
      paths:
      - path: /query
        backend:
          serviceName: api-gateway
          servicePort: 8080
      - path: /playground
        backend:
          serviceName: api-gateway
          servicePort: 8080
---
apiVersion: networking.gke.io/v1beta2
kind: ManagedCertificate
metadata:
  name: fishapp-certificate
spec:
  domains:
  - fishapp.work