apiVersion: mysql.presslabs.org/v1alpha1
kind: MysqlCluster
metadata:
  name: user-db
spec:
  replicas: 1
  secretName: user-db-secret
  podSpec:
    resources:
      requests:
        cpu: 30m
        memory: 300Mi

  volumeSpec:
    persistentVolumeClaim:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi
  mysqlConf:
    character-set-server: utf8mb4
    collation-server: utf8mb4_unicode_ci
# ---
# apiVersion: sql.cnrm.cloud.google.com/v1beta1
# kind: SQLInstance
# metadata:
#   name: sample-mysql3
# spec:
#   databaseVersion: MYSQL_5_7
#   region: asia-northeast1
#   settings:
#     tier: db-f1-micro
#   rootPassword:
#     value: G8XhBRChd2NEJxqr