apiVersion: v1
data:
  DATABASE: pN6ZBn6EDAo1JSb7Wjh3F//07ldmDbIHYSt2/NEn/W0I5P+/ubNIMbciqALnmoN4.gAuH19HWvFFEm4+J.X9yaF4USTO2EgJlHmfv38g==
  ROOT_PASSWORD: v+7OBhlv0R9V70UE1ZBqasMnVydGhJBDoBi2bftDJsL4dhjWBKbq3q/gjhrgxpoV.JOF13S4E7vv7BdD+.vnnoQc90cPh4ecx8mYgp0Q==
kind: Secret
metadata:
  name: user-db-secret
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/fishapp-282106/locations/asia-northeast1/keyRings/fishapp-kubesec-key-ring/cryptoKeys/fishapp-kubesec-crypto-key:CiQAzx2ev0508lcyZXft58hppZjigk9ZT2KjEcRgyDUO1Z0nPBUSSQDRSNMh+2MwfcjEl52L7UQY47W78yV/ThzS5YsgVhj49WdHOujdBfnBVCVMmRhdBzzG0/tDrYD490ueZBfQQrhVo8rJhUeaNVc=
# kubesec:mac:SoAEhlZMpjGba9xX.ingtVaeICbzuQqyETswsqA==