apiVersion: v1
data:
  password: QnLmUyhHjB3RLt2HVLpbodk/RPdaKzT9mU9uQj8LpkOxrDVlvgeoJoEMUwRJe+Op.8uh6viKYazHMHsPY.+UBkOVXlKDBHoAe+Jkfp8Q==
kind: Secret
metadata:
  name: user-kvs-secret
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/fishapp-282106/locations/asia-northeast1/keyRings/fishapp-kubesec-key-ring/cryptoKeys/fishapp-kubesec-crypto-key:CiQAzx2evxgOfZnoBtfZsWbKXyYR/dYHkCknub7rzr73UxfLAekSSQDRSNMhqUzYLIuS+HuiGQGHubUjpkzoqOAWdimaUPor1RoTprpf0MlP/y7cTWf3XOxaADz9S0eQY97Fnxh97FaRSoOTC/z0hLA=
# kubesec:mac:EYeDwsd2bHeQzUnT.We02q3FHV6exLFdc6IIk7g==
