version: '3.4'
services:
  image:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: hot-reload
    volumes:
      - .:/app
    depends_on:
      - image-db

  image-db:
    image: mysql:5.7
    volumes:
      - image-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: image_DB
    ports:
      - "9306:3306"
volumes:
  image-data:
  
networks:
  default:
    external:
      name: fishapp-net
