apiVersion: v1
kind: Service
metadata:
  name: post-db
  labels:
    app: post-db
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: post-db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: post-db
  labels:
    app: post-db
  
spec:
  serviceName: post-db
  selector:
    matchLabels:
      app: post-db
  replicas: 1
  template:
    metadata:
      labels:
        app: post-db
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.17
        args:
        - --default-authentication-plugin=mysql_native_password
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: postapi
                  key: db.pass
          - name: MYSQL_DATABASE
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.name
          - name: TZ
            valueFrom:
                configMapKeyRef:
                  name: overall
                  key: local.tz
          - name: MYSQL_TCP_PORT
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.port
        volumeMounts:
        - name: post-data
          mountPath: /var/lib/mysql
      volumes:
      - name: post-data
        persistentVolumeClaim:
          claimName: post-claim