apiVersion: v1
kind: Service
metadata:
  name: post
  
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 50051
  selector:
    app: post
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post
  labels:
    app: post
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      initContainers:
      - name: wait-post-db
        image: busybox:latest
        command: ["sh", "-c", "until nslookup post-db; do echo waiting for post-db; sleep 2; done;"]
      - name: migrate-post-db
        image: migrate_post_db
        args: ["-database $(DB_DBMS)://$(DB_USER):$(DB_PASS)@tcp($(DB_HOST):$(DB_PORT))/$(DB_NAME)?charset=utf8mb4&parseTime=True&loc=Local -path /sql up"]
        env:
          - name: DB_PASS
            valueFrom:
                secretKeyRef:
                  name: postapi
                  key: db.pass
          - name: DB_DBMS
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.dbms
          - name: DB_USER
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.user
          - name: DB_NAME
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.name
          - name: DB_PORT
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.port
          - name: DB_HOST
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.host
      containers:
      - name: post
        image: post
        tty: true
        ports:
        - containerPort: 50051
        env:
          - name: TZ
            valueFrom:
                configMapKeyRef:
                  name: overall
                  key: local.tz
          - name: DB_PASS
            valueFrom:
                secretKeyRef:
                  name: postapi
                  key: db.pass
          - name: DB_DBMS
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.dbms
          - name: DB_USER
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.user
          - name: DB_NAME
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.name
          - name: DB_PORT
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.port
          - name: DB_HOST
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.host
          - name: DB_CONN_OPT
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: db.conn.opt
          - name: LISTEN_PORT
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: listen.port
          - name: TIMEOUT
            valueFrom:
                configMapKeyRef:
                  name: postapi
                  key: timeout.sec