apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: /data/image-db/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName:  image-db-pv