apiVersion: v1
kind: PersistentVolume
metadata:
  name: post-db-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: /data/post-db/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: post-db-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName:  post-db-pv