apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
  
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/tmp/fishapp-volume/pv001"