apiVersion: v1
data:
  DATABASE: rpR+ifnkA3CiuaUXioJ6NLRYGPYsP54w96P85Mp1rTOvnjSgUMMMZliBYwkQD8sW.dCkhh810xwYguYK9.bqbKH2LPj6lJWpJS+BoKtQ==
  ROOT_PASSWORD: MI5TlPCum/8rPlLsV91SnV0ISFI3sj0Lj4ZzMtHjPE7ftWtcMlCi3SYtvsjfvlEu.Aa9n7+erDyQZ9dAR.FL0CMsSf48hKMprktDYr/g==
kind: Secret
metadata:
  name: image-db-secret
type: Opaque
# kubesec:v:3
# kubesec:gcp:projects/fishapp-282106/locations/asia-northeast1/keyRings/fishapp-kubesec-key-ring/cryptoKeys/fishapp-kubesec-crypto-key:CiQAzx2ev/a/fim2YfnIMGh8xPH7vx59ljJG0AJpcV9WmCUKYsQSSQDRSNMh4vioefLUoSVNnayy8xv5uBRTJBvqPyQxq62ndoeDcnjMrg2VubmDH2EJ0f774xXzEQ3rQpMQsyzObgkWvG1mbcsEkpM=
# kubesec:mac:oj1HYq4bYw9Kgv0m.d1idiTTQQzlrl7iKajR63g==
