
kind: Service
apiVersion: v1
metadata:
  name: image
spec:
  selector:
    app: image
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: fishapp-image-api-account-key
      initContainers:
      - name: init-image-db
        image: busybox
        command: ['sh', '-c', "until nslookup image-db-mysql-master.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
        
      - name: migration
        image: migrate/migrate
        args: ["-source", "github://ezio1119:$(GITHUB_TOKEN)@ezio1119/fishapp/microservices/image/db/sql", "-database", "mysql://root:$(DB_PASS)@tcp(image-db-mysql-master:3306)/$(DB_NAME)", "up"]
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: image-db-secret
              key: ROOT_PASSWORD

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: image-db-secret
              key: DATABASE

        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: overall-secret
              key: GITHUB_TOKEN
      containers:
      - name: image
        image: asia.gcr.io/fishapp-282106/image@sha256:c6b33e2e162be82b8fc46a3a1c264ff8a158ddfc72cdb72dabf9ab73d4a2ad22
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 10
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json

        - name: SV_DEBUG
          valueFrom:
            configMapKeyRef:
              name: overall-config
              key: debug

        - name: DB_HOST
          value: image-db-mysql

        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: image-db-secret
              key: ROOT_PASSWORD

        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: image-db-secret
              key: DATABASE

        - name: GCS_BUCKETNAME
          value: fishapp-282106-image-bucket






