apiVersion: v1
kind: Service
metadata:
  name: auth
  
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth
        tty: true
        ports:
        - containerPort: 8080
        env:
          - name: JWT_KEY
            valueFrom:
                secretKeyRef:
                  name: authapi
                  key: jwtkey
          - name: PORT
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: gin.port
          - name: GIN_MODE
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: gin.mode
          - name: CLIENT_URL
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: client.url
          - name: EXP_SEC
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: idToken.exp.sec
          - name: RT_EXP_SEC
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: rtToken.exp.sec
          - name: TZ
            valueFrom:
                configMapKeyRef:
                  name: overall
                  key: local.tz
          - name: DB_PASS
            valueFrom:
                secretKeyRef:
                  name: authapi
                  key: db.pass
          - name: DB_DBMS
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: db.dbms
          - name: DB_USER
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: db.user
          - name: DB_NAME
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: db.name
          - name: DB_PORT
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: db.port
          - name: DB_HOST
            valueFrom:
                configMapKeyRef:
                  name: authapi
                  key: db.host