name: Api-gateway Build and Publish to GCR

on:
  push:
    paths:
    - 'microservices/api-gateway/**.go'
    - 'microservices/api-gateway/conf/conf.yml'
    - 'microservices/api-gateway/healthcheck.sh'
    - 'microservices/api-gateway/Dockerfile'
    - 'microservices/api-gateway/go.mod'
    - 'microservices/api-gateway/go.sum'
    branches:
    - master

env:
  GCP_PROJECT: fishapp-282106
  IMAGE: api-gateway

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/api-gateway
    steps:
    - uses: actions/checkout@v2
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.PUSH_IMAGE_SA_KEY }}

    - run: |
        gcloud auth configure-docker

    - name: Build
      run: |
        docker build --target prod -t asia.gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA .
    
    - name: Publish
      run: |
        docker push asia.gcr.io/$GCP_PROJECT/$IMAGE:$GITHUB_SHA
# on: [push]

# jobs:
#   test:
#     name: test
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master

#     - name: run test
#       uses: cedrickring/golang-action/go1.13@1.4.1
#       env:
#         GO111MODULE: "on"
#         PROJECT_PATH: "./src"
#       with:
#         args: |
#           go test -coverprofile=cover.out ./...
#           ls

#     - uses: codecov/codecov-action@v1
#       with:
#         token: ${{ secrets.CODECOV_TOKEN }}
#         file: ./cover.out