name: Apply Manifest

on:
  push:
    branches:
      - master
    paths:
    - 'k8s/**'

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_ZONE: asia-northeast1-a
  GKE_CLUSTER: fishapp-cluster

jobs:
  apply-manifest:
    name: Apply Manifest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
    #   with:
    #     version: '290.0.1'
    #     service_account_key: ${{ secrets.GCP_SA_KEY }}

    # - name: setup
    #   run: |
    #     gcloud components install kubectl
    #     gcloud config set project $GKE_PROJECT
    #     gcloud config set compute/zone $GKE_ZONE
    #     gcloud container clusters get-credentials $GKE_CLUSTER
    - name: File From GCP_SA_KEY Env
      run: echo ${{ secrets.GCP_SA_KEY }} | base64 -d | tee ./credentials.json >/dev/null

    - name: Kubesec Decryption
      run: |
        docker run --rm -w /work \
        -v $PWD/credentials.json:/credentials.json \
        -v $PWD/k8s:/work \
        -e GOOGLE_APPLICATION_CREDENTIALS=/credentials.json \
        ezio1119/kubesec sh -c " \
        kubesec decrypt -i api/api-gateway/api-gateway-secret.yml && \
        kubesec decrypt -i api/chat/chat-db-secret.yml && \
        kubesec decrypt -i api/chat/chat-kvs-secret.yml && \
        kubesec decrypt -i api/image/image-db-secret.yml && \
        kubesec decrypt -i api/post/post-db-secret.yml && \
        kubesec decrypt -i api/relaylog/nats-streaming-secret.yml && \
        kubesec decrypt -i api/user/user-db-secret.yml && \
        kubesec decrypt -i api/user/user-kvs-secret.yml && \
        kubesec decrypt -i api/user/user-secret.yml && \
        kubesec decrypt -i overall/overall-secret.yml "

    - name: Apply Manifest
      run: |
        docker run --rm -w /k8s \
        -v $PWD/k8s:/k8s \
        -v $PWD/credentials.json:/credentials.json \
        -e GOOGLE_APPLICATION_CREDENTIALS=/credentials.json \
        ezio1119/cloud-sdk-kubectl-helm sh -c " \
        gcloud auth activate-service-account --key-file=/credentials.json && \
        gcloud config set project $GKE_PROJECT && \
        gcloud config set compute/zone $GKE_ZONE && \
        gcloud container clusters get-credentials $GKE_CLUSTER && \
        kubectl apply -f . --recursive "