name: K8S Apply Manifest

on:
  push:
    branches:
      - master
    paths:
    - 'k8s/**'

env:
  GCP_PROJECT: fishapp-282106
  GCP_ZONE: asia-northeast1-a
  GKE_CLUSTER: fishapp-cluster

jobs:
  apply-manifest:
    name: Apply manifest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: k8s
    steps:
    - uses: actions/checkout@v2

    - name: Generate credentials.json from secrets
      run: echo ${{ secrets.KUBECTL_SA_KEY }} | base64 -d | tee ./credentials.json >/dev/null

    - name: Kubesec decryption
      run: |
        docker run --rm -w /work \
        -v $PWD:/work \
        -e GOOGLE_APPLICATION_CREDENTIALS=/work/credentials.json \
        ezio1119/kubesec sh -c " \
        kubesec decrypt -i api/api-gateway/api-gateway-secret.yml && \
        kubesec decrypt -i api/chat/chat-db-secret.yml && \
        kubesec decrypt -i api/chat/chat-kvs-secret.yml && \
        kubesec decrypt -i api/image/image-db-secret.yml && \
        kubesec decrypt -i api/post/post-db-secret.yml && \
        kubesec decrypt -i api/relaylog/nats-streaming-secret.yml && \
        kubesec decrypt -i api/user/user-db-secret.yml && \
        kubesec decrypt -i api/user/user-kvs-secret.yml && \
        kubesec decrypt -i api/user/user-secret.yml && \
        kubesec decrypt -i overall/overall-secret.yml "

    - name: Apply manifest
      run: |
        docker run --rm -w /k8s \
        -v $PWD:/k8s \
        -e CLOUDSDK_CORE_PROJECT=$GCP_PROJECT \
        -e CLOUDSDK_COMPUTE_ZONE=$GCP_ZONE \
        ezio1119/cloud-sdk-kubectl-helm sh -c " \
        gcloud auth activate-service-account --key-file=credentials.json && \
        rm credentials.json && \
        gcloud container clusters get-credentials $GKE_CLUSTER && \
        kubectl apply -f . --recursive"