name: Terraform Plan

on:
  pull_request:
    branches:
      - master
    paths:
    - 'terraform/**'

env:
  GCP_PROJECT: fishapp-282106
  GCP_REGION: asia-northeast1
  GCP_ZONE: asia-northeast1-a

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: microservices/chat
    steps:
    - uses: actions/checkout@v2

    - name: Generate credentials.json from secrets
      run: echo ${{ secrets.TF_SA_KEY }} | base64 -d | tee ./credentials.json >/dev/null

    - name: plan
      run: |
        docker run --rm --entrypoint "" -w /terraform \
        -v $PWD/terraform:/terraform \
        -v $PWD/credentials.json:/credentials.json \
        -e GOOGLE_APPLICATION_CREDENTIALS=/credentials.json \
        hashicorp/terraform:light sh -c " \
        terraform init && \
        terraform fmt -check && \
        terraform plan -no-color -var 'project=$GCP_PROJECT' -var 'region=$GCP_REGION' -var 'location=$GCP_ZONE' "